# Generated by Django 4.2 on 2023-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_text4",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
