# Generated by Django 4.2 on 2023-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_message_message_text4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
