# Generated by Django 4.2 on 2023-08-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_alter_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="message_text1",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_text2",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_text3",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_text4",
        ),
        migrations.AddField(
            model_name="message",
            name="message_content",
            field=models.CharField(default=" ", max_length=400),
            preserve_default=False,
        ),
    ]
